### ISSUE TITLE
Support multiple tags

### ISSUE THREAD

**Issue by xymor** [steemit/steem-js#131]
Hi,

I'm trying to query by using multiple tags like a join, where the result discussions must contain  all tags:

`steemapi.getDiscussionsByCreated({"tag": ['art','culture'], "limit": 10}, fn)`

Is this possible? Is it a limitation of steem rpc api or steemjs?

**Comment by adcpm** [comment]
Yes this is possible, Golos.io is using it. You can do this using "select_tags" parameter instead of "tag" like this:
`steem.api.getDiscussionsByCreated({"select_tags": ['art','culture'], "limit": 10}, fn)`
see here others params: https://github.com/steemit/steem/blob/865451c5d44903274574df54e9f3451af9570bbf/libraries/app/include/steemit/app/database_api.hpp#L91-L93 .

**Comment by xymor** [comment]
Thanks Fabien, works great.

**Comment by recrypto** [comment]
It doesn't seem to work for me. It just pulls the newly created posts and it doesn't even contain the tags I want to retrieve.

I used this:
steem.api.getDiscussionsByCreated({"select_tags": ['art','culture'], "limit": 10}, fn)

**Comment by xymor** [comment]
Yes, it's not filtering. Check this runnable sample: 

https://fiddle.jshell.net/h9jej56j/5/

**Comment by bonustrack** [comment]
Hum right, for some reason `filter_tags`, `select_tags` or `select_author` params are not working while its working on Golos. The functionality is probably not fully implemented on Steem.

**Comment by recrypto** [comment]
Hopefully this get fixed. :( This is really a useful feature to narrow down the query.

**Comment by bonustrack** [comment]
I opened an issue here https://github.com/steemit/steem/issues/1233

**Comment by recrypto** [comment]
Thanks! I'm gonna check that from time to time.

**Comment by recrypto** [comment]
@bonustrack I think they are not supporting this feature any longer. :( https://github.com/steemit/steem/issues/1233#issuecomment-312347216

**Comment by bonustrack** [comment]
Yep :(. You need to rely on private database to do same. Maybe this will help https://steemit.com/steemdata/@furion/steemdata-meets-sbds-sql-users-rejoice

**Comment by recrypto** [comment]
Thanks @bonustrack for this. This will help as supplementary solution for my app for sorting out posts based on tags.

**Comment by recrypto** [comment]
@bonustrack SteemData SBDS is not 100% synced up with Steem blockchain. I ended up using SteemSQL by arcange. Thanks again. :D

**Comment by potadibyo** [comment]
Hey @bonustrack @xymor @recrypto , how can  I  display my post using steemjs??
I search alot but still yet to solve it..

**Comment by marce1994** [comment]
> Yes this is possible, Golos.io is using it. You can do this using "select_tags" parameter instead of "tag" like this:
> `steem.api.getDiscussionsByCreated({"select_tags": ['art','culture'], "limit": 10}, fn)`
> see here others params: https://github.com/steemit/steem/blob/865451c5d44903274574df54e9f3451af9570bbf/libraries/app/include/steemit/app/database_api.hpp#L91-L93 .

thank you man :):):):)
