### ISSUE TITLE
Image crossOrigin policy

### ISSUE THREAD

**Issue by jackchalat** [steemit/steem-js#137]
This is not directly about the code. 

I'm experimenting with loading images from https://steemitimages.com into HTML5 canvas. However, I am unable to do so because the server does not allow any crossOrigin request. 

Is there any way you guys can help me with this? More about CORS enabled image: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by adcpm** [comment]
This is not related to Steem.js, i think this GitHub is more appropriate: https://github.com/steemit/condenser.
