### ISSUE TITLE
get_account_history with wring information

### ISSUE THREAD

**Issue by AugustoL** [steemit/steem-js#142]
#### Expected behavior

Receive the next 10 posts after 12240294 block using  `{"id":1,"method":"get_account_history","params":["augustol","12240294","10"]}`

#### Actual behavior

Receiving the posts with lower block number

#### How to reproduce

 if you try `{"id":1,"method":"get_account_history","params":["augustol","12240294","10"]}`
you will see that the first result has a lower block number is higher than 12240294

```
 [
    [568, {
      "trx_id": "ef27af0ff7d09f98e02160352ec1c926021a98f0",
      "block": 12233137,
      "trx_in_block": 10,
      "op_in_trx": 0,
      "virtual_op": 0,
      "timestamp": "2017-05-25T08:35:18",
      "op": ["custom_json", {
        "required_auths": [],
        "required_posting_auths": ["augustol"],
        "id": "follow",
        "json": "[\"follow\",{\"follower\":\"augustol\",\"following\":\"sarasate\",\"what\":[\"blog\"]}]"
      }]
    }]
```

**Comment by roadscape** [comment]
Here are the parameters for `get_account_history`:

```
      /**
       *  Account operations have sequence numbers from 0 to N where N is the most recent operation. This method
       *  returns operations in the range [from-limit, from]
       *
       *  @param from - the absolute sequence number, -1 means most recent, limit is the number of operations before from.
       *  @param limit - the maximum number of items that can be queried (0 to 1000], must be less than from
       */
      map<uint32_t, applied_operation> get_account_history( string account, uint64_t from, uint32_t limit )const;
```

(It paginates by sequence numbers, not by block numbers!)

**Comment by AugustoL** [comment]
thanks @roadscape , and what should I use as sequence number? what does it mean?

**Comment by roadscape** [comment]
If an account has had 5k operations, the sequence numbers would be 0 to 4999.

You can call `get_account_history account -1 1000` to get the latest 1000 items, and you should see the sequence numbers in the response to keep paginating further back.
