### ISSUE TITLE
Issue in Broadcast Parameters (Posting Comments)

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#151]
From last few days I'm working on steem methods. What I found was there is no proper documentation for the parameters used in broadcast methods.

Eg. 
**steem.broadcast.comment(
                 ' 5J9--------3emc', //wif
                  ' ',   //parentAuthor
                  'steemit', //parentPermlink
                  'holwylb', //author
                   'render-en-cinema-4d',  //permlink
                    'Render en cinema 4d',   //title
                     ' ',    //body
                     ' ',     //jsonMetadata
function(err, result) {
console.log(err, result);
});**

Q) Whatever I want to **comment** will come inside **_body_** parameter or in **_jsonMetadata_**?

I have tried both but getting error "3030000 tx_missing_posting_auth: missing required posting authority" .
Any other key is also required for doing comments?
Can anyone plz share working eg. for the same and other examples related to broadcast methods.

Thanks in advance..

**Comment by adcpm** [comment]
The comment content has to be inside `body` parameter. `jsonMetadata` parameter is an object with post details. You need only a private posting WIF to broadcast a comment. Here is an example how to do:

```
steem.broadcast.comment(
  '5Jd...', // Your posting wif
  'siol', // Parent Author
  'test', // Parent Permlink
  'pj1423', // Your username
  'this-is-a-test', // Your post permlink
  '', // Title
  'This is a test!', // Body
  { tags: ['test'], app: 'steemjs/test' }, // Json Metadata
  function(err, result) {
    console.log(err, result);
  }
);
```

We updated the file `/examples/broadcast.html` on this repo to include an example of comment operation, you can checkout the file here: https://github.com/steemit/steem-js/blob/361a172d33d04889c1315c3056830701c7bf8eb8/examples/broadcast.html and test it localy.

**Comment by PJ1423** [comment]
Hey thanks buddy.. it worked..

It would be very helpful if you can explain how to post blogs and how can we follow and unfollow users.

**Comment by adcpm** [comment]
For broadcast a post you need also to use `comment` operation. Leave `parentAuthor` + `parentPermlink` empty and add a `title`. Like this:
```
steem.broadcast.comment(
  '5Jd...', // Your posting wif
  '', // Parent Author
  '', // Parent Permlink
  'pj1423', // Your username
  'this-is-a-test-post', // Your post permlink
  'This is a test post', // Title
  'Just trying to post using steem.js', // Body
  { tags: ['test'], app: 'steemjs/test' }, // Json Metadata
  function(err, result) {
    console.log(err, result);
  }
);
```

Follow and unfollow works with `custom_json` operation here is the format:
```
var json = JSON.stringify(
  ['follow', {
    follower: 'YOUR_USERNAME',
    following: 'USERNAME_TO_FOLLOW',
    what: ['blog'] // Use an empty array "[]" to unfollow
  }]
);
steem.broadcast.customJson(
  'YOUR_POSTING_WIF',
  [], // Required_auths
  ['YOUR_USERNAME'], // Required Posting Auths
  'follow', // Id
  json, //
  function(err, result) {
    console.log(err, result);
  }
);
```

I've updated this page with follow/unfollow https://github.com/steemit/steem-js/blob/04fc58e5eeef6f4fbcc5194da35da07cadb59ff1/examples/broadcast.html#L44-L85

**Comment by PJ1423** [comment]
Thanks

Just used above method to post data but every time getting same error.

steem.broadcast.comment(
  '5Jd...', 
  '',
  '', 
  'pj1423', 
  'test-post-to-check-steem-method', 
  'Test post to check steem method', 
  'Just trying to post using steem.js', 
  { tags: ['test'], app: 'steemjs/test' }, 
  function(err, result) {
    console.log(err, result);
  });

assert_exception: Assert Exception permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size.

**Comment by adcpm** [comment]
My mistake, actually `parentPermlink` has to be filled. It's used as main tag of the post. I've updated the example in my last comment and added it on the page `examples/broadcast.html`

**Comment by PJ1423** [comment]
Thank you
Really very helpful.. 👍 

Can you please tell one more thing. While using Login method it is always returning **true**, whether giving correct steem name and password or not.

`steem.api.login(
'pj1423',  `//username`
'5J9...', //password
 function(err, result) {
  console.log(err, result);
});`

Is there any other method for login and what are the parameters will we get after login.

**Comment by adcpm** [comment]
**It's not safe** to run this method with your password as it's sent plain to the node websocket. This method will only return `true`, its used in intern with empty values to enable broadcast. You don't need to login for broadcast an operation.

**Comment by PJ1423** [comment]
Yes I'm able to use all broadcast methods but I was making a small app using these methods and what I want is a login screen where all steem members can login using there user name and password. 

Is there any other way to do the same.
I'm stuck in this process of login.
Please help.

**Comment by PJ1423** [comment]
In following method Required_auths will be blank and what parameters will come inside  Required Posting Auths.

steem.broadcast.customJson(
    postingWif,
    [], // Required_auths
    [follower], // Required Posting Auths
    'follow', // Id
    json, //
    function(err, result) {
      console.log(err, result);
    }
  );

**Comment by adcpm** [comment]
For login i recommend you to use steemconnect.com for secure the keys of your users, you can find a tutorial here: https://steemit.com/tutorial/@krnel/tutorial-how-to-add-steemit-login-to-your-site-with-steemconnect

Required posting auths require your username inside an array. `following` is the user you want to follow/unfollow.

**Comment by PJ1423** [comment]
Hey Fabien
Thanx :-)
This tutorial was very helpful and now I'm able to login through my steem id and password and redirect to different page.

Now I want to create my own login page where user can login using there steem id and password.

From where I can get API's or  steemConnect methods related to Login and forgot password, which I can use in my login page as I don't want to redirect user to steem login page.

Please guide.

**Comment by 4leem** [comment]
Will the `body` in comment accept HTML & markdown (if used with backtick - ES6)?
