### ISSUE TITLE
[Question] Regarding "comment beneficiaries"

### ISSUE THREAD

**Issue by recrypto** [steemit/steem-js#157]
Hello,

I have some questions regarding about comment beneficiaries. Can you please help me clarify this?

## **Scenario 1:**
If I set the parameter for "**percent_steem_dollars**" to 10000 or **100**%, then I set a beneficiary to a username called "**recrypto**" with weight 1000 or 10%.

When the payout is due and the breakdown should look like this?
**Author:** 6500 or **65%**
**Curators:** 2500 or **25%**
**recrypto:** 1000 or **10%**

## **Scenario 2:**
If I set the parameter for "**percent_steem_dollars**" to 5000 or **50**%, then I set a beneficiary to a username called "**recrypto**" with weight 1000 or 10%.

When the payout is due and the breakdown should look like this?
**Author**: 6500 or **65%**
**Curators**: 2500 or **25%**
**recrypto:** 1000 or **10%** (Will this be 5% SBD and 5% VEST or STEEM Power or 10% STEEM Power)

## Follow up question
Is that right? Once I set the beneficiaries on comment_options, it's automatically distributed?

## Source
https://github.com/steemit/steem-js/blob/master/test/comment.test.js#L46

Thanks! Greatly appreciate it.
ReCrypto

**Comment by feruzm** [comment]
It looks like it won't effect beneficiary rewards only author rewards. Beneficiary rewards are always in SP.
