### ISSUE TITLE
npm intall fails (Windows/VS2017) due to bad postinstall

### ISSUE THREAD

**Issue by MWaser** [steemit/steem-js#158]
#### Expected behavior

Executing command 'npm install steem@"0.5.13" should install steem

#### Actual behavior

====Executing command 'npm install steem@"0.5.13"  '====

'scripts' is not recognized as an internal or external command,
> steem@0.5.13 postinstall C:\Source\Repos\SteemBot\SteemBot\node_modules\steem
operable program or batch file.
> scripts/post-install.js
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "steem@0.5.13"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! steem@0.5.13 postinstall: `scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the steem@0.5.13 postinstall script 'scripts/post-install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.

#### How to reproduce

Visual Studio 2017, new NodeJS project, add steem to package.json

**Comment by MWaser** [comment]
I'm assuming that all you have to do is add the command node into the post-install command in package.json so it works across all platforms . . . .

**Comment by MWaser** [comment]
ARGH!  No . . . . the whole build chain is UNIX specific . . . .  :-(

**Comment by nil1511** [comment]
@MWaser Can you try using `npm install steem@0.5.13-beta.2`?

**Comment by MWaser** [comment]
That worked perfectly.  Thank you!
