### ISSUE TITLE
How to resteem any post using steem-js?

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#163]
I have gone through broadcast methods but was unable to find how to resteem any post?

**Comment by adcpm** [comment]
Resteem use `custom_json` operation with posting wif. See this example:
```
const json = JSON.stringify(['reblog', {
  account: username,
  author: 'timsaid',
  permlink: 'myth-or-fact-25-bats-are-blind'
}]);

steem.broadcast.customJson(privPostingWif, [], [username], 'follow', json, (err, result) => {
  console.log(err, result);
});
```
Test it on JSFiddle: https://jsfiddle.net/bonustrack/bpcpd874/

**Comment by PJ1423** [comment]
Thanks buddy

**Comment by aminraisy** [comment]
@bonustrack dear Fabien ... have you tested it ? I test it in your jsffidle ... not working ? even with my own username and posting key doesn't work

**Comment by t3ran13** [comment]
@aminraisy  it is ok in golos, i think the same for steem
