### ISSUE TITLE
Public Profile Setting and Update Password using steemjs

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#165]
Hello

Just wanted to know how can we update public profile and how to generate password and update it using steemjs.
Please guide.
Thanks.

**Comment by adcpm** [comment]
You need to use the operation `accountUpdate` for change public profile. Here is how to do:
```
var jsonMetadata = { profile: { name: 'PJ142' } };

steem.broadcast.accountUpdate(
  active_or_owner_priv_wif,
  username,
  undefined, // Set to undefined so account authority dont change
  undefined,
  undefined,
  memo_key,
  jsonMetadata,
  function (err,  result) {
    console.log(err, result);
  }
);
```
For generate new password you can copy this code https://github.com/adcpm/sc2/blob/4a1030aff2b59c01cd0ece10cc265643e02dc58f/src/utils/auth.js#L54-L58
Then with the password you can generate public keys for each authority and use `accountUpdate` operation like this:
```
var publicKeys = steem.auth.generateKeys(account.name, account.password, ['owner', 'active', 'posting', 'memo']);
var owner = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.owner, 1]] };
var active = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.active, 1]] };
var posting = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.posting, 1]] };

steem.broadcast.accountUpdate(
  active_or_owner_priv_wif,
  username,
  owner,
  active,
  posting,
  publicKeys.memo,
  jsonMetadata,
  function (err,  result) {
    console.log(err, result);
  }
);
```

**Comment by nsaklecha** [comment]
Thanks for replying. 👍 
But I'm having few doubts regarding Update Password Method.

Generate new password method generates 32 char string. Will it be ok to use that string as our new password, as my current password consist of 51 char string.

Also want to know that in "_account.password_" in **_publicKeys_** , I have to use my new generated password or old password. 

With accountUpdate method all four keys are getting updated, will it update my new password and what will be the value of jsonMetadata in accountUpdate method.

**Comment by adcpm** [comment]
There is no restriction about password. It can be 1 char string too. 32 char is safe enought. You should be using your new password in `account.password` when you update password but sign the operation with an active/owner WIF from old password. The value of jsonMetadata must be same as your current account json_metadata attribute, unless you want to change it.

**Comment by tomobrien2004** [comment]
When I do the accountUpdate like described I get the following error:

RPCError: missing required active authority:Missing Active Authority

It gives that error regardless of whether I use the 'owner' or 'active' private key.

I get the privateKeys like so:

`var privateKeys = steem.auth.getPrivateKeys(account.name, account.private_key);`

And the method looks like this:

`steem.broadcast.accountUpdate(
    privateKeys.active,
    account.username,
    undefined,
    undefined,
    undefined,
    privateKeys.memoPubkey,
    json_metadata,
    function(err, result) {
        console.log(err, result);
    }
});`

I used the memoPubkey because when I used the private memo key it gave the following error:
Error: transaction.operations = account_update,[object Object]	 cause: account_update.memo_key = 5JDrTk8ZErmAPqkKMw9JpW9R7sh2XBTx9m3mTuweZF5H4Y4zCSH	 cause: Expecting key to begin with STM, instead got 5JD

Any ideas why it is giving the 'required active authority error?'

**Comment by mycatnamedweb** [comment]
I am unable to reset the private keys, any help with my code snippet please?

<code>
const { key_utils, PublicKey, PrivateKey } = require('steem/lib/auth/ecc');

const newlyGeneratedPrivateKey= `P${key_utils.get_random_key().toWif()}`;

var publicKeys = steem.auth.generateKeys('pitaly-florida', newlyGeneratedPrivateKey, ['owner', 'active', 'posting', 'memo']);
var owner = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.owner, 1]] };
var active = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.active, 1]] };
var posting = { weight_threshold: 1, account_auths: [], key_auths: [[publicKeys.posting, 1]] };
var memo = publicKeys.memo;
var jsonMetadata = {};

console.log({ owner, active, posting, memo }, 'Prepped keys.');

steem.broadcast.accountUpdate(
  'P5Jabcabcabcabc123123123', // @testuser's private owner key
  'testuser',
  owner,
  active,
  posting,
  memo,
  jsonMetadata,
  (err,  result) => {
    console.log(err, result);
  }
);
</code>

Result:
```
{"err":{"name":"AssertionError","actual":128,"expected":149,"operator":"==","message":"Expected version 128, instead got 149","generatedMessage":false}}
```

**Comment by Jolly-Pirate** [comment]
@mycatnamedweb you're not using the correct owner key at the line
`'P5Jabcabcabcabc123123123', // @testuser's private owner key`
The error `Expected version 128` means it's not a proper WIF.

Here's a revised code with some improvements:

```
const steem = require('steem');

var account = 'testuser';
var currentPassword = 'whatever it is';

var currentPrivateKeys = steem.auth.getPrivateKeys(account, currentPassword, ['owner', 'active', 'posting', 'memo']);
var currentOwnerKey = currentPrivateKeys.owner;

// new password
var suggestedPassword = steem.formatter.createSuggestedPassword(); // createSuggestedPassword is 32 characters in length
var newPassword = 'P' + steem.auth.toWif(suggestedPassword); // add P, convert SuggestedPassword to WIF

var newKeys = steem.auth.getPrivateKeys(account, newPassword, ['owner', 'active', 'posting', 'memo']); // get the private and public keys

// SAVE THIS OUTPUT INFORMATION AND DO NOT LOSE IT
console.log(`
Current owner key : ${currentOwnerKey}
New password      : ${newPassword}
New keys          : ${JSON.stringify(newKeys, null, 1)}`);

// this is not needed anymore because we already got the pubkeys from steem.auth.getPrivateKeys()
// var publicKeys = steem.auth.generateKeys(account, newPassword, ['owner', 'active', 'posting', 'memo']);

var owner = {weight_threshold: 1, account_auths: [], key_auths: [[newKeys.ownerPubkey, 1]]};
var active = {weight_threshold: 1, account_auths: [], key_auths: [[newKeys.activePubkey, 1]]};
var posting = {weight_threshold: 1, account_auths: [], key_auths: [[newKeys.postingPubkey, 1]]};
var memo = newKeys.memoPubkey;
var jsonMetadata = {};

// broadcast
steem.broadcast.accountUpdate(
  currentOwnerKey, // @testuser's CURRENT private owner key
  account,
  owner,
  active,
  posting,
  memo,
  jsonMetadata,
  (err, result) => {
  console.log(err, result);
});

```

**Comment by mycatnamedweb** [comment]
Thanks! I solved in another way but I will give it a try soon 👍
