### ISSUE TITLE
Comments on post/blog

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#167]
var tag = 'esteem-features',
username = '@good-karma',
permlink = 'esteem-feature-set-11-login-with-qr-code-add-multiple-accounts-2017611t111958860z'

steem.api.getState('/tag/username/permlink', function(err, result) {
	console.log(err, result);
});

-------------------------------------------------------------
I want replies on post and this method is giving desired output but with other unwanted data.
Is there any particular method to find replies for particular post?

**Comment by adcpm** [comment]
There is the method `getContentReplies` for it see:
```
var parent = 'good-karma';
var parentPermlink = 'esteem-feature-set-11-login-with-qr-code-add-multiple-accounts-2017611t111958860z';

steem.api.getContentReplies(parent, parentPermlink, (err, result) => {
  console.log(err, result);
});
```
https://jsfiddle.net/bonustrack/84dmnoLj/3/

**Comment by PJ1423** [comment]
I have used this method but this gives only main comments. If there is a reply to a particular comment then we are not getting from this method, where to get those comments which are children to main parent comment.

**Comment by bonustrack** [comment]
When you use `getState` you have all the comments. They appear in same level you can filter them based on `id`, `depth` and `root_comment` parameters to recreate the structure in multi level. The way i would do: first load the root comments by filtering the ones having `depth == 1`. Then for each of these root comments, load sub comments by filtering the one having `root_comment == id` . Hope it help.

**Comment by potadibyo** [comment]
dear @bonustrack  I use getContentReplies by get only those replies which replied by others , not those which replied user itself,
please solve me this issue
