### ISSUE TITLE
Cant vote via api.

### ISSUE THREAD

**Issue by Losiara** [steemit/steem-js#168]
#### Expected behavior

Make vote with this code.

```
var steem = require('steem');
 
var wif = steem.auth.toWif(username, password, 'posting');
steem.broadcast.vote(wif, voter, author, permlink, weight, function(err, result) {
    console.log(err, result);
});

```

Makes upvote.
#### Actual behavior

Produced very long error

    { Error: 3030000 tx_missing_posting_auth: missing required posting authority....

#### How to reproduce

Just run this code with own username password

**Comment by PJ1423** [comment]
You don't have to generate wif . Use your password/posting-wif.
It will do.

**Comment by Losiara** [comment]
They are same. Both variants don't work.

**Comment by recrypto** [comment]
You might have used the wrong type of key or used the public one. You should use the private one.

**Comment by Losiara** [comment]
Used key is 100% right. Checked and rechecked!

**Comment by PJ1423** [comment]
https://github.com/steemit/steem-js/blob/master/examples/broadcast.html

example is given and it worked for me.
