### ISSUE TITLE
Is there any way to get feed from specific account?

### ISSUE THREAD

**Issue by imkimchi** [steemit/steem-js#169]
I'm wondering if I can put my username in `query` param so I get feed contents from specific account and how can I get posts from specific blog without permalink as well?

honestly the documentation is the worst written document I've ever seen. every single API functions needs `query` param but there's no explanation about what to put in the param.

**Comment by adcpm** [comment]
You can use `getDiscussionsByFeed` to get user feed and `getDiscussionsByBlog` to get user blog. `query` parameter must be an object with `query.tag` as username. Here is how to do:

```
var query = {
  tag: 'ned',
  limit: 10
};

steem.api.getDiscussionsByFeed(query, function (err, result) {
  console.log(err, discussions);
});

steem.api.getDiscussionsByBlog(query, function (err, result) {
  console.log(err, discussions);
});
```

**Comment by andrienpecson** [comment]
I have this error wherein some of the retrieved discussions are retrieved are not from the author?

 var query = {
        tag: 'ned',
        limit: 4
    };

steem.api.getDiscussionsByBlog(query, function (err, response) {
  //Codes here
}

**Comment by alephchain** [comment]
it's a resteem

**Comment by antonchanning** [comment]
@andrienpecson If you don't want to include resteems, just posts authored by user, then use getDiscussionsByAuthorBeforeDate instead:

		steem.api.getDiscussionsByAuthorBeforeDate(username, lastPermlink, '2100-01-01T00:00:00', count,	function(err, result){ ... }); 

lastPermlink should be an empty string when you get the most recent. Then use the oldest post permlink returned when you want to get the next batch...

**Comment by powerpoint45** [comment]
> @andrienpecson If you don't want to include resteems, just posts authored by user, then use getDiscussionsByAuthorBeforeDate instead:
> 
> ```
> 	steem.api.getDiscussionsByAuthorBeforeDate(username, lastPermlink, '2100-01-01T00:00:00', count,	function(err, result){ ... }); 
> ```
> 
> lastPermlink should be an empty string when you get the most recent. Then use the oldest post permlink returned when you want to get the next batch...

this is no longer working no matter the parameters. Anyone know why?   `{"name":"RPCError","code":-32603,"data":{"error_id":"04b0b636-b655-472b-ad34-0eafdba62f08","jussi_request_id":"000664238044085943"}}`
