### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by bycz6** [steemit/steem-js#173]
I'm getting this error when trying to install! 
```
bycz@ubuntu:~$ sudo npm install steem --save

> steem@0.5.15 postinstall /home/bycz/node_modules/steem
> cross-env scripts/post-install.js

/usr/bin/env: ‘node’: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/home/bycz/package.json'
npm WARN bycz No description
npm WARN bycz No repository field.
npm WARN bycz No README data
npm WARN bycz No license field.
npm ERR! Linux 4.8.6-x86_64-linode78
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "steem" "--save"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! steem@0.5.15 postinstall: `cross-env scripts/post-install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the steem@0.5.15 postinstall script 'cross-env scripts/post-install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env scripts/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steem
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bycz/npm-debug.log
```

you could find the debug file attached.
[npm-debug.log.txt](https://github.com/steemit/steem-js/files/1086641/npm-debug.log.txt)

**Comment by nil1511** [comment]
Try to install without `sudo` like this `npm install steem --save` because most likely node is not installed for root user.

**Comment by bycz6** [comment]
I already tried. Same result.

Cumprimentos/Best regards,
Rafael Mateus.


Em 20/06/2017 05:03, "Nilesh Suthar" <notifications@github.com> escreveu:

Try to install without sudo like this npm install steem --save because most
likely node is not installed for root user.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/steemit/steem-js/issues/173#issuecomment-309638859>,
or mute
the thread

**Comment by nil1511** [comment]
Can you try running `ln -s /usr/bin/nodejs /usr/bin/node` and try again

**Comment by bycz6** [comment]
![image](https://user-images.githubusercontent.com/23620619/27591287-1e019acc-5b49-11e7-9528-bad8db0de6a6.png)

**Comment by bycz6** [comment]
solved. 

i've to change the name in package.json

**Comment by nil1511** [comment]
@bycz6 Can you tell what you have changed? 
It will be helpful for someone else. 
Thanks.

**Comment by bycz6** [comment]
I already said.
I've to change  the "name" in package.json for another
