### ISSUE TITLE
Debian (Jessie) install error

### ISSUE THREAD

**Issue by RicRock** [steemit/steem-js#187]
Full Log => [npm-debug.txt](https://github.com/steemit/steem-js/files/1100401/npm-debug.txt)

ric@Zbox:~$ npm install steem --save
npm WARN engine cross-env@5.0.1: wanted: {"node":">=4.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
\
> steem@0.5.18 postinstall /home/ric/node_modules/steem
> cross-env scripts/post-install.js

/home/ric/node_modules/steem/node_modules/cross-env/dist/variable.js:14
var pathLikeEnvVarWhitelist = new Set(['PATH', 'NODE_PATH']);
                                  ^
ReferenceError: Set is not defined
    at Object.<anonymous> (/home/ric/node_modules/steem/node_modules/cross-env/dist/variable.js:14:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ric/node_modules/steem/node_modules/cross-env/dist/index.js:11:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! steem@0.5.18 postinstall: `cross-env scripts/post-install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the steem@0.5.18 postinstall script.
npm ERR! This is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env scripts/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "steem" "--save"
npm ERR! cwd /home/ric
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ric/npm-debug.log
npm ERR! not ok code 0

**Comment by Hunternnm** [comment]
Update your node and npm version. Your version is very old

**Comment by yamadapc** [comment]
The minimal supported version is v4, as stated in cross-env's warning message
