### ISSUE TITLE
How do I get a record of my feed?

### ISSUE THREAD

**Issue by Hunternnm** [steemit/steem-js#189]
Hi! I could not figure out how to get the data from my ауув - all the posts of those I follow. For example, as here: https://steemit.com/@hunternnm/feed 
Thank you!

**Comment by bonustrack** [comment]
You need to use `getDiscussionByFeed` method. Here is an example: https://jsfiddle.net/bonustrack/24b7ky2s/

**Comment by Hunternnm** [comment]
Sorry, found right after he wrote here
