### ISSUE TITLE
This relative module was not found (webpack)

### ISSUE THREAD

**Issue by Hunternnm** [steemit/steem-js#196]
Hi! When you import a steem `import steem from 'steem'` and then at compilation, i receive an error:
```
This relative module was not found:
* ./methods in ./node_modules/steem/lib/api/index.js
```
If add `.json` in line import (https://github.com/steemit/steem-js/blob/master/src/api/index.js#L8)- its work. Am I doing something wrong?

**Comment by yamadapc** [comment]
You should both have the `json-loader` in the configuration (without `exclude: /node_modules/`) and make sure your webpack configuration doesn't exclude the `.json` extension in the `resolve: { extensions: [...]}` bit.

If you share your webpack configuration that'd be helpful.
