### ISSUE TITLE
User issued assets

### ISSUE THREAD

**Issue by gropox** [steemit/steem-js#197]
Hi,

with next golos HF will be introduced UIA (user issued assets). It will be possible to create own currencies (assets). There will be a bunch of new operations and data types. 

asset_create_operation,
asset_update_operation,
asset_update_bitasset_operation,
asset_update_feed_producers_operation,
and so on

There are also some changes on existing marked operations and so on. Steemit does not have such feature and I don't saw it on the road map of steem. 

There is the golos branch commit containing changes

https://github.com/GolosChain/golos/commit/9a4ecb3e609971bb70a139aff4a6e3b2c19b9a09

Whould it possible to integrate new operations and data types into steem-js? Probably because of new operations steem-js have to be branched. 

I would do this integration by my self, could you then briefly explain, how to generate files with operations, and steeps to do it properly?

Thanks

**Comment by bonustrack** [comment]
These method will not supported by Steem.js directly you will need to fork it and update few files.

1: Add the new operations manually here:
https://github.com/steemit/steem-js/blob/master/src/broadcast/operations.json

2: Update serializer. There is a method on steemd called `js_operation_serializer` to generate this file based on blockchain code.  
https://github.com/steemit/steem-js/blob/master/src/auth/serializer/src/operations.js

3: Then update the list here with new operations: https://github.com/steemit/steem-js/blob/dafb00ffd8f022d5143fe5e4c39a95334d28c680/src/auth/serializer/src/ChainTypes.js following the same order than here: https://github.com/steemit/steem-js/blob/master/src/auth/serializer/src/operations.js#L708-L765

Hope this help.

**Comment by gropox** [comment]
Thank you, I will try it.

**Comment by yamadapc** [comment]
Closing
