### ISSUE TITLE
getBlock and getTrx return 'Object'.

### ISSUE THREAD

**Issue by littleanti** [steemit/steem-js#199]
When I try to watch block and transaction payload.

getBlock and getTransaction returns like below.
Is it correctly returns blocak and transaction??

**getBlock:**
null { previous: '00baade5b5c5cc766fcbc60f1e27b01dcf87c504',
  timestamp: '2017-05-25T09:29:24',
  witness: 'jesta',
  transaction_merkle_root: '259de4aaa01e96d4d7b7df3954afbe2063cca6f2',
  extensions: [],
  witness_signature: '205cb67cf7a6084883e21f9504c48a5bb33726c92765e6a61d7848477357d64c1961a7dcf56ff20235c7b6d345a33bc11cdfca64d1329ab660cfd314f38db100cb',
  transactions: 
   [ { ref_block_num: 44517,
       ref_block_prefix: 1993131445,
       expiration: '2017-05-25T09:29:51',
       operations: [Object],
       extensions: [],
       signatures: [Object] },
     { ref_block_num: 44516,
       ref_block_prefix: 1044743385,
       expiration: '2017-05-25T09:29:33',
       operations: [Object],
       extensions: [],
       signatures: [Object] },
     { ref_block_num: 44517,
       ref_block_prefix: 1993131445,
       expiration: '2017-05-25T09:29:36',
       operations: [Object],
       extensions: [],
       signatures: [Object] },
     { ref_block_num: 44517,
       ref_block_prefix: 1993131445,
       expiration: '2017-05-25T09:29:36',
       operations: [Object],
       extensions: [],
       signatures: [Object] },
     { ref_block_num: 44516,
       ref_block_prefix: 1044743385,
       expiration: '2017-05-25T09:29:48',
       operations: [Object],
       extensions: [],
       signatures: [Object] },
     { ref_block_num: 44517,
       ref_block_prefix: 1993131445,
       expiration: '2017-05-25T09:29:36',
       operations: [Object],
       extensions: [],
       signatures: [Object] } ],
  block_id: '00baade60b87a9682a597c1291d5de341f94f1ae',
  signing_key: 'STM7BV1MSfK2RCxqZKQ3CNYfa95ZLksNAqXNLMLfctpKPxMsrZgaQ',
  transaction_ids: 
   [ '44cf62f6cec500d8bee01ef52346552fbb98c040',
     '22da7e14fe0f50f4b57b042650edec2ca2a1fd3f',
     '33292dfa0dbaf8b564b0775f6b4f21f5888d988f',
     'aeefe7564dadcba5bb6066725364a14048bff300',
     '81b3724e02d9dc0835df2ccead2f42913f285eef',
     'f048c81f7764b2381afa541481697f1f451c6b4d' ] }

**getTransaction:**
null { ref_block_num: 0,
  ref_block_prefix: 0,
  expiration: '1970-01-01T00:00:00',
  operations: [],
  extensions: [],
  signatures: [],
  transaction_id: '0000000000000000000000000000000000000000',
  block_num: 0,
  transaction_num: 0 }

Thank you.
Yoon.

**Comment by yamadapc** [comment]
That looks correct, yes. When using the callback API, the first callback argument is either an error or `null` and the second is the result. If the issue is `[Object]` in the log, that's just how the logger prints it; you can see the full payload with `JSON.stringify(result, null, 2)` if you want.

There's also a promise API for all methods accessed through appending `Async` to the end of their names; i.e. `getTransactionAsync(trx).then((result) => {...})`
