### ISSUE TITLE
Add example of using with Webpack

### ISSUE THREAD

**Issue by yamadapc** [steemit/steem-js#200]
Every now and then people are having problems with the `json-loader` and this library. Providing an example project would be a nice addition.

#196

**Comment by bonustrack** [comment]
Isn't something we can solve in our end? Both users having trouble with `json-loader` been able to fix it by adding `.json` the import line.

**Comment by yamadapc** [comment]
Hm, I don't think so... You'll always need `json-loader`. Users that fix it by adding `.json` have incorrect resolve configurations that ignore that `.json` extension. That is different behavior to node.js.

We could avoid it altogether by not using JSON or avoid resolving trouble by adding the extension.

Having an example is nice regardless IMO
