### ISSUE TITLE
RPC FetchError

### ISSUE THREAD

**Issue by bonustrack** [steemit/steem-js#205]
RPC transport failing with this error from time to time:

`State/store error:  FetchError: invalid json response body at https://jussi.steemitdev.com reason: Unexpected token < in JSON at position 5 Error`

You need to send a big bunch of requests to experience this issue. 

The question is, is it related to Steem.js?

**Comment by yamadapc** [comment]
We could handle the error but this is this `steem` HTTP server responding with HTML. Maybe we should check the status code; in the end I think we'll throw an error either way.

**Comment by bonustrack** [comment]
This issue has been solved
