### ISSUE TITLE
How do I claim rewards?

### ISSUE THREAD

**Issue by msg768** [steemit/steem-js#215]
Is it possible to claim rewards through this API? I would be very thankful if someone directed me to an example if it's possible! Thank you in advance.

**Comment by bonustrack** [comment]
You can claim reward using the method `claimRewardBalance`. Here is an example:
```
steem.broadcast.claimRewardBalance(privatePostingWif, 'username', '0.000 STEEM', '0.000 SBD', '123.093932 VESTS', function(err, result) {
  console.log(err, result);
});
```

**Comment by msg768** [comment]
Thanks! How can I find out the amount that is available? Is there anyway to tell it to claim whatever is available? If not, how do I calculate the available amount?

**Comment by bonustrack** [comment]
You can get user current reward balances using the method `getAccounts`. The parameters are: "reward_sbd_balance", "reward_steem_balance" and "reward_vesting_balance".

**Comment by msg768** [comment]
Perfect! Thanks heaps :]
