### ISSUE TITLE
NOTHING WORKS!

### ISSUE THREAD

**Issue by msg768** [steemit/steem-js#221]
Nothing seems to be working anymore. I keep getting the following error:

<code> Error: The WS connection was closed before this operation was made</code>
<code>    at WebSocket.<anonymous> (steem.min.js:5) undefined </code>

**Comment by bonustrack** [comment]
The default websocket set on Steem.js `wss://steemd.steemit.com` is not fully operational at the moment unfortunately. You can use your own node or wait.

**Comment by msg768** [comment]
How do I use my own node? How many nodes are out there? Where can I get a list of all nodes?

**Comment by bonustrack** [comment]
There is few tutorials on steemit.com for setup your own node, here is one: https://steemit.com/steem/@jesta/building-a-high-availability-steemd-node-for-web-apis . I don't have a list of others public node.

**Comment by msg768** [comment]
Thanks a lot! I found one that's working:
<code>steem.config.set('websocket','wss://steemdev.steemit.com');</code>
