### ISSUE TITLE
SteemJ not working on Google App Engine

### ISSUE THREAD

**Issue by jan10101** [steemit/steem-js#225]
#### Expected behavior

Would be nice if I could use SteemJ in my maven project (Java) running on Google App Engine

#### Actual behavior

A class used by SteemJ seems to be restricted by App Engine and SteemJ can not be executed. The class is: java.lang.management.ManagementFactory

The error message thrown by App Engine:

Could not reconfigure JMX java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory is a restricted class. Please see the Google  App Engine developer's guide for more details.

#### How to reproduce

Try to call SteemJConfig.getInstance(); in an App Engine project

**Comment by bonustrack** [comment]
This is Steem.js repository not Steemj, i've moved the issue here: https://github.com/marvin-we/steem-java-api-wrapper/issues/53
