### ISSUE TITLE
Power up and down through API's

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#233]
Hi

In wallet section I found two options for **power up** and **power down**. 

I found this api

var steemPower = steem.formatter.vestToSteem(vestingShares, totalVestingShares, totalVestingFundSteem);

this will convert Vest To Steem.
Can I use this api for power down? 
If yes then please can any one share parameter details.

Please suggest which **steem api** to be used and its parameters.

Thanks

**Comment by bonustrack** [comment]
Here is how to power up
```
steem.broadcast.transferToVesting(wif, 'fabien', 'fabien', '1.000 STEEM', function(err, result) {
  console.log(err, result);
});
```
And this how to power down
```
steem.broadcast.withdrawVesting(wif, 'fabien', '100000.000000 VESTS', function(err, result) {
  console.log(err, result);
});
```

You can find the balance in VESTS of an account using `steem.api.getAccounts`. Or convert vest to Steem using `steem.formatter.vestToSteem`.

**Comment by PJ1423** [comment]
Thanks a lot buddy.

Can you please tell one more thing that which method can be used to withdraw steem.

**Comment by bonustrack** [comment]
You can use the method `transfer` for withdraw Steem to another account.
```
steem.broadcast.transfer(wif, from, to, '1.001 STEEM', memo, function(err, result) {
  console.log(err, result);
});
```

**Comment by hemangmehta** [comment]
@bonustrack suppose my friend transfer steem from his steem account to my steem account using this api.
 
so if i am not wrong please correct me,
parameter for , `steem.broadcast.transfer` will ne as below - 

```
wif - it will be  "Active, private Key"
from - "username of my friend's account'
to - "username of my account"
amount - Amount he want to send me
memo - something like notes for me he wants to add, and it will display under `Topup` in my wallet history
```

Can you please confirm above parameters make sense ?
