### ISSUE TITLE
getAccountsAsync doesn't return result for some users

### ISSUE THREAD

**Issue by vsternbach** [steemit/steem-js#234]
#### Expected behavior

When making API call to steem.api.getAccountsAsync() with one user (i.e. gr82bu) returns result

#### Actual behavior

When making API call to steem.api.getAccountsAsync() with other user (i.e. toprublogs) returns empty array as result

#### How to reproduce

Just to make an API call as described

P.S. same behavior for getAccounts API call

**Comment by bonustrack** [comment]
Are you still having an issue with it? Can you show me your code? I'm not able to reproduce this issue, `toprublogs` account work for me with `getAccounts` or `getAccountsAsync`.

**Comment by vsternbach** [comment]
My bad, I had a typo of the username in the code)
