### ISSUE TITLE
transferFromSavings method giving error.

### ISSUE THREAD

**Issue by PJ1423** [steemit/steem-js#237]
var wif = 5j.... // wif key,
from = "user1",
to = "user1",
amount = "10.000 STEEM",
memo = "",
requestId = 1560689745   //some random 10 digit no.

steem.broadcast.transferFromSavings(wif, from, requestId, to, amount, memo, function(err, result) {
  console.log(err, result);
});

Getting error : requestId not an integer.

Am I doing anything wrong here? Is there any way to generate requestId?

Thank you.

**Comment by bonustrack** [comment]
I've been able to broadcast a transaction using the same parameters see: https://steemdb.com/block/14881222 tx id = 9aec6bd8da7dcc7a694af5c847b3f0142f4f6ccf
Normally this error would appear if you set requestId as string like this `requestId = '1560689745'` instead of `requestId = 1560689745`.

**Comment by PJ1423** [comment]
Is there any method for generating requestID or we can give random uint32 no. How to maintain uniqueness?

**Comment by PJ1423** [comment]
thankyou very much.
