### ISSUE TITLE
steem.api.getAccounts only outputs "undefined" or "NaN"

### ISSUE THREAD

**Issue by Neo93** [steemit/steem-js#238]
Hey, I have a problem which I'm trying to solve for hours and hours now but still nothing..

#### Expected behavior

I'm trying to get the recent posts (which works) and the authors (which also works) and filter them through steempower (which doesn't work.)

#### Actual behavior

For this I use "steem.api.getAccounts" and "steem.api.getDynamicGlobalProperties". Together they don't work at all but seperetally the nearest I came was to show the VEST-amount of the author. But 90% of the time I get "undefined" or "NaN" in the consoloe.

#### How to reproduce

The code is fairly simple. This methods gets triggered after I get the posts. 

```
  function metricsAuthor(posts){
    var deferred = Q.defer();
    for (var i = 1; i < posts.length; i++){
      var user = posts[i].author.toString();
      console.log(getUserAccount(user));
    }
    deferred.resolve(true);
    return deferred.promise;
  }

function getUserAccount(user){
    steem.api.getAccounts([user], function(err, result) {
         return result[0].vesting_shares;
    });
  }
  
```

The nearest I came to my goal was when from 300 - about 10 VESTS were put into the console.

**Comment by bonustrack** [comment]
You cannot use console.log() with an async function. When console.log() is triggered the response from getAccounts not yet arrived. You can use async/await to solve this issue like this: https://jsfiddle.net/nyqxf4rf/ or use a different structure for your code. This is not an issue of Steem.js

**Comment by CryptoSharon** [comment]
```js
function getUserAccount(user) {
  return new Promise((resolve, reject) =>
    steem.api.getAccounts([user], (e, r) =>
      e ? reject(e) : resolve(r[0].vesting_shares)
}
function metricsAuthor(posts) {
  posts.forEach(post =>
    getUserAccount(post.author.toString()).then(console.log)
}
```
