### ISSUE TITLE
npm install steem --save gives error

### ISSUE THREAD

**Issue by Tyrone333** [steemit/steem-js#240]
#### Expected behavior

it should install the package

#### Actual behavior

i get this error and it stops:
```
steem@0.6.3 postinstall /Users/tyrone3/luckysteemian/steemlib/FinalSteem/express-cc/node_modules/steem
postinstall-build lib && cross-env scripts/post-install.js

internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
    at spawn (/Users/tyrone3/luckysteemian/steemlib/FinalSteem/express-cc/node_modules/cross-env/node_modules/cross-spawn/index.js:17:18)
    at crossEnv (/Users/tyrone3/luckysteemian/steemlib/FinalSteem/express-cc/node_modules/cross-env/dist/index.js:31:38)
    at Object.<anonymous> (/Users/tyrone3/luckysteemian/steemlib/FinalSteem/express-cc/node_modules/cross-env/dist/bin/cross-env.js:6:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steem@0.6.3 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the steem@0.6.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
#### How to reproduce

i have no idea

**Comment by Sekhmet** [comment]
This is an issue with `npm@5.4.0`. It should work with `npm@5.4.1` or you can use `npm@5.3.0` instead.

**Comment by relativityboy** [comment]
Can you update to an even version of node? 6 or 8? 6 should be a pretty
easy transition, and you'll get the LTS phase goodness.

On Fri, Sep 8, 2017 at 10:04 AM, Wiktor Tkaczyński <notifications@github.com

**Comment by bonustrack** [comment]
@relativityboy did you experienced the same issue using Node < 6 ?

**Comment by Tyrone333** [comment]
thanks for the fast respons! i will test it asap!

**Comment by relativityboy** [comment]
@bonustrack I haven't used it with anything lower than 7

**Comment by Tyrone333** [comment]
it worked for me with npm5.3, thanks for the great help.
I now have another problem, maybe you guys can help me with this as well. I wanted to test it with an easy call like this:
steem.broadcast.vote(
			'5J3CwitGuiTGJzB8aA8RAAA1EPJqjkR4GXv*************', //postingkey
			'holunder', //upvoter
			'jack.the.ripper', //author
			'my-daily-top-9gag-posts-23', //permlink 
			10000, 
			function(err, result) {
  			console.log(err, result);
		});
But when i do so, i get this error:
 generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 128,
  expected: 2,
  operator: '==' } undefined

I have no clue what it is, when i run this code in my html version, it works fine!
