### ISSUE TITLE
Why can I not load the steem-js library from the CDN external server

### ISSUE THREAD

**Issue by Boontjie** [steemit/steem-js#245]
I am expecting the CDN connection to load the library without errors into gapps ,i.e.
eval(UrlFetchApp.fetch('https://cdn.steemjs.com/lib/latest/steem.min.js').getContentText());

Currently the import is giving an invalid 'property ID error'.

For reference
eval(UrlFetchApp.fetch('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js').getContentText())
Works.

Could you explain why I am getting this error?

**Comment by Boontjie** [comment]
For interest sake, it is because the steem-js implementation uses browser DOM objects, which is something like GAS will not recognize.  I would need to create my own REST API server using python or a full node.js (or other) to parse the websocket output into a structured JSON response

**Comment by bonustrack** [comment]
I see. There is a REST API you can use see here: https://api.steemjs.com/getAccounts?names[]=fabien
https://v2.steemconnect.com/docs/steemjs
Also the blockchain has JSON-RPC API See https://steemit.com/steem/@xeroc/steem-api

**Comment by Boontjie** [comment]
Thank you.  I was not aware. I will look at the links
