### ISSUE TITLE
Follower/Following Count

### ISSUE THREAD

**Issue by sjkelleyjr** [steemit/steem-js#252]
Is there an API call that returns the number of followers/following of an account?  I see the database API and python libraries support this,  but does the steemjs library?

**Comment by sjkelleyjr** [comment]
Just found it, my bad.

**Comment by karimation** [comment]
@sjkelleyjr  try this: 
```
steem.api.getFollowCountAsync('username',function(err, result) {
    console.log(err,result)
  });
```
