### ISSUE TITLE
Is there a faster way to get a users posts?

### ISSUE THREAD

**Issue by sjkelleyjr** [steemit/steem-js#260]
I'm trying to build an app whereby a user can see the posts of all the people they're following.  However, these API calls are taking a minute and a half to return for a user who's following ~200 users.

Currently I'm using:	
`followingUsernames.forEach(async username => {
		let usersPosts = await steem.api.getDiscussionsByBlogAsync({tag:username,limit:10));
	})`

Where followingUsernames is an array of usernames.  

Is there a better way to do this? I'm using React Native and I'd ideally like to show the most recent posts made by people the user is following first in a ScrollView (similar to a twitter feed) but I can't make a user wait 2 minutes to see this data.

**Comment by bonustrack** [comment]
You can use `getDiscussionsByFeed({ tag: username })` to get all your following posts.

**Comment by sjkelleyjr** [comment]
OMG!...duh...I knew that already from a previous project... ha ha

Thanks!
