### ISSUE TITLE
steem.config.set() does not reinitialize the transports like steem.api.setOptions() does

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem-js#262]
I'm currently working on allowing users to select which steemd node they'd like to use with the Vessel wallet. Currently I'm using `steem.api.setWebSocket(url)` to change the endpoint to the user's choice, but I'm getting depreciation messages to switch to `steem.config.set('websocket', url)`. 

I cannot use `steem.config.set('websocket', url)`, since it doesn't reinitialize the transports like `setOptions` does. Until the new method of setting the config updates the transports, we are forced to continue using `setWebSocket` or `setOptions` regardless of it's deprecated state.

#### Expected behavior

`steem.config.set('websocket', url)` when called should also call the same methods that `setOptions` does [within the API](https://github.com/steemit/steem-js/blob/master/src/api/index.js#L157). 

#### Actual behavior

Using `steem.config.set('websocket', url)` after the initial connection to steemd has been made does not change the URL that the websocket uses. It continues to remain connected to the initial connection string,  regardless of changes to the data.

#### How to reproduce

```
<html>
  <head>
    <script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script>
  </head>
  <body>
    <script>
      // Make request to detault (steemd.steemit.com)
      steem.api.getAccounts(['steemit'], function(err, response){
        // Wait for response from server, then change websocket to new server (wallet.steem.ws)
        steem.config.set('websocket', 'wss://wallet.steem.ws')
        // Make call to new server
        steem.api.getAccounts(['jesta'], function(err, response){
          console.log(err, response);
        });
      });
    </script>
  </body>
</html>
```

The above script, albeit crude, will remain connected to `steemd.steemit.com` even though the websocket has been changed. 

#### Environment information

ReactJS + Electron + steem-js 0.6.4

**Comment by bonustrack** [comment]
It should work if you trigger `steem.api.stop();` after changing config.

**Comment by aaroncox** [comment]
That'll prove to be a nice workaround. 

Should we close this or leave it open as it's something that would be nice to have at some point?

**Comment by bonustrack** [comment]
@aaroncox You can close this issue, I suggest you to use `steem.api.setOptions({ url: 'https://...' });` it allow both WS or HTTP node urls. `steem.config.set()` for set a different node is too much confusing.
