### ISSUE TITLE
steemPower formatter 

### ISSUE THREAD

**Issue by Tyrone333** [steemit/steem-js#266]
Hello, I am trying to get the steemPower from the API, I first use this:

steem.api.getAccounts();

Then I try to use the information I get there to us it for the formatter, but I can't find out what are exactly the 3 parameters:

var steemPower = steem.formatter.vestToSteem(vestingShares, totalVestingShares, totalVestingFundSteem);
console.log(steemPower);

vestingShares: I think I know that one -> vesting_shares;
totalVestingShares: I have no idea;
totalVestingFundSteem: I have no idea;

Help is much appreciated

**Comment by bonustrack** [comment]
You can get `total_vesting_shares` and `total_vesting_fund_steem` values using the function
```
steem.api.getDynamicGlobalProperties((err, result) => {
  console.log(result.total_vesting_shares, result.total_vesting_fund_steem);
});
``` 
See: https://api.steemjs.com/getDynamicGlobalProperties
