### ISSUE TITLE
"Invalid sequence tag" for signing key STM1111111111111111111111111111111114T1Anm

### ISSUE THREAD

**Issue by vikxx** [steemit/steem-js#267]
Broadcasting any other keys works well, but
broadcasting a ```STM1111111111111111111111111111111114T1Anm``` key by calling ```steem.broadcast.witnessUpdate``` 

causes an error: Invalid sequence tag

**Comment by Jolly-Pirate** [comment]
Getting that same error too. Any fix yet?
