### ISSUE TITLE
Npm library not updated with steemd.steemit.com beeing retired

### ISSUE THREAD

**Issue by stephane303** [steemit/steem-js#312]
https://www.npmjs.com/package/steem
It still using the default wss://steemd.steemit.com

**Comment by thrize** [comment]
+1 on this, steem-js is currently broken when used via NPM

**Comment by bobinson** [comment]
+1

**Comment by Amanej** [comment]
What is a decent steemd node now ?

**Comment by thrize** [comment]
They've retired the use of websockets completely in favor of using RPC, so it's not just a case of pointing to an operational node, there's major internal code changes needed. They were merged into master in PR #300 for example. We just need them to publish a release but I think they're holding it up because the CI tests are failing, maybe there are more significant errors.

I wonder if we can contribute in some way to speed this up, the popular Steem FOSSbot voter is broke as a result.

**Comment by beaugettiz** [comment]
When it is fixed, what is the procedure for updating the heroku install of FOSSbot?

**Comment by thrize** [comment]
That's off topic, keep an eye on the FOSSbot repo or my account (at)personz on steemit

**Comment by penguinpablo** [comment]
+1

**Comment by thrize** [comment]
For the moment you can use this code to use @Gandalf-the-Grey 's server instead

```steem.config.set('websocket','wss://gtg.steem.house:8090');```

**Comment by lmiller1990** [comment]
@thrize this server is not working for me either. Is there another public/free server we can use to try the API out?

**Comment by Gandalf-the-Grey** [comment]
@lmiller1990 that server is up and running, so if you have troubles connecting to it, then you should check for possible errors on your side. You can try json-rpc 2.0 endpoint (i.e. not websocket) `https://api.steemit.com`)

**Comment by thrize** [comment]
Yep, it certainly is. But I didn't realize before that you actually can use the RPC server as @Gandalf-the-Grey says, you just have to use a different function to config is, e.g.:

```steem.api.setOptions({ url: 'https://api.steemit.com'});```

Thanks to @aaroncox for pointing that out 😅

**Comment by DestBest** [comment]
Be aware if you use this code:
`steem.api.setOptions({ url: 'https://api.steemit.com'});`

The empty error response for certain function is `""` instead of the previous `null`

Using `steem.api.setOptions({ url: 'https://api.steemit.com'});` I get the same empty error response as before

**Comment by grigio** [comment]
Tried to fix with:

```
    steem.api.setOptions({ url: 'https://api.steemit.com'});
    steem.api.getContent(rootPost.author, rootPost.permlink).then(post => { ...
```

but I get this error

```
Uncaught TypeError: Cannot read property 'then' of undefined
```

**Comment by bonustrack** [comment]
@grigio You need to add `Async` suffix on method to get promise, example: `steem.api.getContentAsync(...).then(...)`.

**Comment by bonustrack** [comment]
Closing this issue, the last version of `steem` (`0.7.1`) has been updated with the endpoint `https://api.steemit.com` by default.
