### ISSUE TITLE
steem.api.getContent calls callback twice if successful

### ISSUE THREAD

**Issue by thrize** [steemit/steem-js#327]
This is particularly difficult in my use case, using wait.for which does not like a callback being called more than once.

#### Expected behavior

steem.api.getContent calls callback function once only if successful

#### Actual behavior

steem.api.getContent calls callback function twice if successful, once with function args (null, data) and a second time with function args (null, null)

#### How to reproduce

Make any use of steem.api.getContent function, e.g.

```
steem.api.getContent("personz", "where-the-thunderdome-flags-at-lethargy-and-niceness-against-flagging", function (err, result) {
    callback(err, result);
});
```

where some ```callback``` function must be defined.

#### Environment information

Bug exhibited in v0.6.4

**Comment by bonustrack** [comment]
I'm not able to reproduce this issue with `0.6.4` or `0.7.1`, is it possible that `getContent` been triggered twice in your code? Also i recommend you to update to the latest version.

**Comment by thrize** [comment]
Weird, it's not happening now that I upgraded to 0.7.1

It was definitely happening on 0.6.4, I checked again, as described. But fixed by upgrade so fixed.

Thanks for checking it out
