### ISSUE TITLE
Incorrect Reputation Calculated using Steem Js

### ISSUE THREAD

**Issue by DoctorLai** [steemit/steem-js#344]
Here is the code to reproduce:

```
    steem.api.getAccounts(["mkt"], function(err, result) {
        if (!err) {
            console.log(result[0].reputation);
            console.log(steem.formatter.reputation(result[0].reputation));
        } 
    });
```

It will output to console: 

```
10004392664120
70
```

From the steemd.com we can verify @mkt 's Reputation is:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518034140/oh5z0okibghmqora6g9x.png)

But the correct reputation is 61 instead of 70. 

# Environment
Browser: Chrome v64
OS: Win10 64 bit

![](https://steemitimages.com/DQmPyEeD2KAGGW8iSa2KsvYMTYYuHuTNMrfV6vEeszc73Q8/image.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/incorrect-reputation-calculated-using-steem-js">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by DoctorLai** [comment]
Fix proposed at:  https://github.com/steemit/steem-js/pull/345

**Comment by BartolomeoItaliano** [comment]
I will check it in a few days.

**Comment by DoctorLai** [comment]
@BartolomeoItaliano  as @mkt's reputation score has changed. so here is the one-line code to reproduce it:

```
console.log(steem.formatter.reputation(10004392664120));
```

This should output 61 but, it outputs 70.

**Comment by DoctorLai** [comment]
Another similar report of the bug:   https://utopian.io/utopian-io/@kodeblacc/the-extension-shows-incorrect-reputation-on-my-profile-banner

**Comment by BartolomeoItaliano** [comment]
Hi, sorry for not resolving your issue. Amount of work I recently have stops me from doing so. 
And I cannot get in any possible way access to this library to help all of you. No one answers my calls :(

**Comment by DoctorLai** [comment]
You could easily verify it in [SteemJs Editor.](https://helloacm.com/tools/steemit/steemjs/?s=//this%20prints%20incorrect%2070%20instead%20of%2061%0Alog(steem.formatter.reputation(10004392664120));)

**Comment by steemchiller** [comment]
The same goes for a value like '1000995952600'. The result should be '52' but is '61'. It has to do with the four leading digits (1000 in this case) that are being used for further calculations.

The result for Math.log(leadingDigits) / Math.log(10) is < 3.0, but needs to be >= 3.0 here. I think it would work when we change the following line: 

const log = Math.log(leadingDigits) / Math.log(10);

to something like:
const log = Math.log(leadingDigits + 0.000000001) / Math.log(10);

Hope this helps ;)

**Comment by ety001** [comment]
Has merged.
