### ISSUE TITLE
UnableToResolveError: Unable to resolve module `events`

### ISSUE THREAD

**Issue by dancherb** [steemit/steem-js#355]
Same issue as previously posted by @shango44 and closed - wasn't able to comment on his issue so re-posting, thanks!

Expected behavior
I should receive this in prompt:
Bundlingindex.js[development, non-minified] 100.0% (728/728), done.

Actual behavior
Receiving Error:
Bundling 'index.js' [development, non-minified] 33.9% (476/818), failed. error: bundling failed: UnableToResolveError: Unable to resolve module 'events' from '...\node_modules\steem\lib\api\index.js': Module does not exist in the module map

How to reproduce
Install

npm install -g react-native-cli
react-native init steemapp
npm install steem --save
Code

import steem from 'steem'

Run

react-native run-android

Environment information
Windows 10 64
Node v8.6.0
Npm 5.6.0
Steem v0.6.7

**Comment by cutemachine** [comment]
I have the same problem. Why has this issue been closed? Is there a solution to the problem?
Thanks.
