### ISSUE TITLE
What's the best way to get a specific post with its permlink?

### ISSUE THREAD

**Issue by jeffbernst** [steemit/steem-js#360]
I'm trying to find the best way to retrieve a specific post with its permlink.

#### Expected behavior

Based on the [documentation](https://developers.steem.io/), it seems like the following should work:

```javascript
import steem from 'steem';
steem.api.setOptions({ url: 'https://api.steemit.com' });

steem.api.getDiscussionsByAuthorBeforeDate({author: authorName, startPermlink: permlink}, function(err, result) {
	console.log(err, result)
});
```

#### Actual behavior

I get the following error when I try this:

```
Uncaught (in promise) TypeError: callback is not a function at http.js:101
```

#### Environment information

I'm running this in a React project on my Mac. What would be the correct approach for this?

Thanks!

**Comment by c0d3ster** [comment]
Another way to retrieve the information without creating a date variable would be to use the getContent function.  Below is a sample of how to use this with Bluebird promises and ES6 syntax.

```
steem.api.getContentAsync(author, permlink)
.then(postObject => console.log(postObject))
.catch(error => console.log(error));
```

**Comment by jeffbernst** [comment]
That's awesome, thanks! Will definitely try this out.
