### ISSUE TITLE
getContentReplies need from and limit arguments

### ISSUE THREAD

**Issue by Cengkaruk** [steemit/steem-js#366]
#### Expected behavior
In trending post, you get a lot of replies. Should can be limit via arguments.

```
steem.api.getContentReplies(author, permlink, from, limit function(err, result) {
  console.log(err, result);
});
```

#### Actual behavior

```
steem.api.getContentReplies(author, permlink, function(err, result) {
  console.log(err, result);
});
```

#### Environment information

```
$ node -v
v9.5.0
$ npm -v
5.6.0
```

**Comment by BartolomeoItaliano** [comment]
Hi @Cengkaruk you are right with your concernes and there is another method in library:

```
steem.api.getRepliesByLastUpdate(startAuthor, startPermlink, limit, function(err, result) {
  console.log(err, result);
});
```

Which does exactly what you ask about. 

I can suspect steemit, busy, strimi and most of the bigger webpages use this.
