### ISSUE TITLE
crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by irelandscape** [steemit/steem-js#398]
#### Expected behavior

Should be able to import steem library into my vue,js project.

#### Actual behavior

Getting the following error:
[Vue warn]: Error in mounted hook: "TypeError: crypto.randomBytes is not a function"
on the following line:
var steem = require('steem') 

The exception is thrown from the nodeRandom function in secure-random.js.
I put a breakpoint in that function and I can see that require('crypto') returns an empty object:

```console
> crypto
<- {}
```

#### How to reproduce

I seem to be able to reproduce the problem by just invoking:
require('steem')

The reported error is in secure-random.js, in the function nodeRandom.

I have verified that I can invoke the crypto.randomBytes function directly from my application.
The following works:
console.log(require('crypto').randomBytes(64))
so I'm wondering if the steem library somehow messes up crypto.

#### Environment information

Using node 8.10 on Ubuntu 18.04
Application uses the Quasar UI framework with vue.js.

**Comment by Sekhmet** [comment]
This seems to be vue-cli specific problem. If application is running or built using vue-cli `process.pid` is set to `1`.  `secure-random` checks for `process.pid` and if it is a number it assumes you are running inside of node, which causes the library not to work.

https://github.com/jprichardson/secure-random/blob/master/lib/secure-random.js#L20

**Comment by Sekhmet** [comment]
I have filled a patch to secure-random. If it gets merged & released I will create a PR for steem-js to use new version. In other case I will release the new version myself so it is usable with vue-cli.

**Comment by BartolomeoItaliano** [comment]
I think I've solved your problem already try to use this version of steem-js:

`npm install steem-js-refactored 
`
tell me if it resolves your problem

**Comment by irelandscape** [comment]
Hi thanks. I'll try to confirm the fix.

**Comment by irelandscape** [comment]
Hi BartolomeoItalia,

Unfortunately I still get the same error on the line:
```
var steem = require('steem-js-refactored')
```

**Comment by miikkikiikki** [comment]
Exactly the same problem, try to start my vue.js project with steem-js, but get an error.

**Comment by Sekhmet** [comment]
You can use https://github.com/jnordberg/dsteem
It should be more than enough for most usecases.

**Comment by nothingismagick** [comment]
@irelandscape - I have resolved this by the way with dsteem (using quasar 0.17.15):

```js
// /src/plugins/dsteem.js
import { Client } from 'dsteem'

export default ({ app, router, Vue }) => {
  const steemClient = new Client('https://api.steemit.com')
  Vue.prototype.$steemClient = steemClient
}

// script part in a vue SFC
export default {
  name: 'Index',
  data () {
    return {
      props: {
        maximum_block_size: this.main()
      }
    }
  },
  methods: {
    main: async function () {
      await this.$steemClient.database.getChainProperties().then((props) => {
        console.log(`Maximum blocksize consensus: ${props.maximum_block_size} bytes`)
        this.props = props
      })
    }
  }
}
```

**Comment by joticajulian** [comment]
The solution of @Sekhmet worked for me. I had to clone both secure-random and steem-js, make the [changes in secure-random](https://github.com/jprichardson/secure-random/pull/12), install it on steem-js and build steem-js.
PS: I can not use dsteem because i want to use `steem.memo.encode` and `steem.memo.decode`, and these functions are not in dsteem.
