### ISSUE TITLE
Exception: Cannot read property 'total_vesting_shares' of undefined 

### ISSUE THREAD

**Issue by JuergenSimon** [steemit/steem-js#423]
Sorry for the sloppy report, but I am in a hurry. Encountered this problem:

Take the result of `appicsSteem.steem.api.getAccounts(['leoney'])` and use `appicsSteem.steem.formatter.estimateAccountValue(account);`

I get the following error:

```
TypeError: Cannot read property 'total_vesting_shares' of undefined 
at vestingSteem (/app/node_modules/steem/lib/formatter.js:20:41) 
at /app/node_modules/steem/lib/formatter.js:90:27 
...
```
#### Environment information
node 8.11.4
steem.js 0.7.3

**Comment by bra1n** [comment]
It seems like this is caused when the Steem API does not return the appropriate `props` Property for a formatter.js triggered `/@username` API call. Maybe some better error handling in the formatter.js would be useful here.

**Comment by bra1n** [comment]
Actually, that line seems to be the cause of the whole issue: https://github.com/steemit/steem-js/blob/11b4458719865013005cc7b7f5a1581d7ed1e9e7/src/formatter.js#L75
`/@{username}` is not how ES6 string patterns work, correct would be: `/@${username}`

**Comment by chrisli30** [comment]
The fix is legit but no one merge it?

**Comment by bra1n** [comment]
Seems like the maintainers have lost interest in this project.
