### ISSUE TITLE
[HELP] Issue in connecting with private steem node !

### ISSUE THREAD

**Issue by yashbhavsar007** [steemit/steem-js#426]
What i actually want is to make own block explorer for steem private node.
I am trying to connect steem-js with my private net which working fine with dsteem but when i connect with steem-js and trying to access steem.api.getConfig this method i got this error "Error: Bad Cast:Invalid cast from type 'array_type' to Object" and i also not able to access get_reward_fund method which gives me this error "Exception:method_itr != api_itr->second.end(): Could not find method get_reward_fund"

**Comment by roadscape** [comment]
Have you specified `"useAppbaseApi": true` in the config?

**Comment by yashbhavsar007** [comment]
@roadscape solved this issue this was raised due to pinging wrong server url i was pinging https url which was not working hence i tried http and it's working now and closing this issue !
