### ISSUE TITLE
Steem API Changes

### ISSUE THREAD

**Issue by JuergenSimon** [steemit/steem-js#428]
Hello,

according to this document, there are going to be changes to the steem API:
https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com

* Have these changes already been accommodated in the steem.js library? 
* Are there any changes I need to make to code using steem.js?

**Comment by roadscape** [comment]
The changes were implemented via overridden routes, so steem-js should still be fully compatible. When hivemind gets an updated API, steem-js will need to support namespaced methods.
