### ISSUE TITLE
getDiscussionsByVotes (and by other methods like Cashout) not working

### ISSUE THREAD

**Issue by kravtsov200439** [steemit/steem-js#430]
#### Expected behavior

A returning of a list of posts, maximum of 100, in the form of JSON objects, with all their attributes such as author, active-votes etc

#### Actual behavior

An error reading:

Error: Assert Exception:_tags_api: tags_api_plugin not enabled.
    at new e (steem.min.js:4)
    at steem.min.js:4 undefined

#### How to reproduce

type this into a JS console with steem allready present

steem.api.getDiscussionsByVotes({tag: "givexp", limit: 100}, function(a, b){console.log(a,b)})

#### Environment information

I am using a XAMPP localhost server, Windows 8.1 and I imported steemjs with
<script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script>

my steem.config is:
{
  transport: "http",
  websocket: "wss://gtg.steem.house:8090",
  uri: "https://api.steemit.com",
  url: "",
  dev_uri: "https://api.steemitdev.com",
  stage_uri: "https://api.steemitstage.com",
  address_prefix: "STM",
  chain_id: "0000000000000000000000000000000000000000000000000000000000000000"
}

**Comment by wehmoen** [comment]
This is not a steem-js issue. The RPC node you are using does not have these plugins enabled. This is not a bug. The RPC node returns the expected result here.

**Comment by kravtsov200439** [comment]
wait so which RPC node does use the plugins and how do I switch nodes?

**Comment by wehmoen** [comment]
I don't think any node has it enabled at the moment. If you want to use this the best thing would be to setup your own RPC node I guess.
