### ISSUE TITLE
STEEMJS CDN is down

### ISSUE THREAD

**Issue by Rishi556** [steemit/steem-js#449]
#### Expected behavior
CDN should return minified js file.

#### Actual behavior
Site is down.

#### How to reproduce
Go to : https://cdn.steemjs.com/lib/latest/steem.min.js.

**Comment by jredbeard** [comment]
Hi @Rishi556 - thanks for reporting this. The Steemit team actually does not host steemjs.com, so failures there are out of our control. I believe this has been the Steemconnect team in the past and we've reached out to them about it.

As a long term solution, we've updated the README to suggest using this URL instead which will update with each release:

https://cdn.jsdelivr.net/npm/steem/dist/steem.min.js

You should use this new URL instead in your browser based projects.
