### ISSUE TITLE
Tag new release for 0.7.7

### ISSUE THREAD

**Issue by stoodkev** [steemit/steem-js#450]
#### Expected behavior

New release is done for major code changes.

#### Actual behavior

No release for 0.7.7

This is particularly sensitive for our Steem extensiosn SteemPlus and Steem Keychain. To make these extensions available on Firefox we need to link third party releases.

**Comment by jredbeard** [comment]
Hi @stoodkev - we publish releases to both `@steemit/steem-js` on NPM as well as to `steem`:

https://www.npmjs.com/package/@steemit/steem-js
https://www.npmjs.com/package/steem

Both of these were updated to 0.7.7 17 days ago. Do you mean something else?

**Comment by stoodkev** [comment]
Hi @jredbeard, I meant a release here on Github.
When we publish an extension to FF, they will check that the `steem.min.js` corresponds to an official release.

**Comment by jredbeard** [comment]
Sure - I've made a corresponding (github) release here: https://github.com/steemit/steem-js/releases/tag/v0.7.7

Let me know if you need anything else @stoodkev
