### ISSUE TITLE
Is Cdn.steemjs.com Down Right Now? Ping failing and loading of script failing (was not the case several days ago)

### ISSUE THREAD

**Issue by littlemiddlebiddle** [steemit/steem-js#452]
#### Expected behavior

Cdn.steemjs.com loads

#### Actual behavior

'Loading failed for the <script> with source “https://cdn.steemjs.com/lib/latest/steem.min.js”.'

#### How to reproduce

1. Add <script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script> to a page
2. Load the page

Alt:
1. Open command prompt
2. Ping cdn.steemjs.com ( yields "Ping request could not find host steemjs.com. Please check the name and try again.")

#### Environment information

Windows 10
Node 10.16.0

**Comment by Smittyvb** [comment]
Duplicate of #449.

**Comment by littlemiddlebiddle** [comment]
Thanks for the update!
