### ISSUE TITLE
steem.broadcast.transfer private message not working

### ISSUE THREAD

**Issue by oguzdelioglu** [steemit/steem-js#482]
#### Expected behavior

"#EmThs9Xy5Vrbbw6gdAyvcV8kCbk9eYnTeowSXFeCvB7oNSv9oxEpPupz6u3GqmwPFBZGqg63fA8oj9vTH5ZUczRJnp1qLVjjMjtELRWkAcuFt9yyaCqcb9UW7GmhQyCgG"

#### Actual behavior

"# this is a private message"

#### How to reproduce

steem.broadcast.transfer private message not working.

**Comment by ety001** [comment]
Hi, @oguzdelioglu 
Do you mean this?

```
const senderWif = '5JdeC9P7Pbd1uGdFVEsJ41EkEnADbbHGq6p1BwFxm6txNBsQnsw';
const senderPubkey = 'STM8m5UgaFAAYQRuaNejYdS8FVLVp9Ss3K1qAVk5de6F8s3HnVbvA';
const receiverPubkey = 'STM7oNQjZPQWkM4Qa3AZUP5WYRjkdYaGR1ciXepATvZ5xns2sPL5D';
const receiverWif = '5HzbTLPQM9qv5iBavcvTGNr9UrRbCWeNGdY1pEqKxTS567sh51F';

const msg = '# this is a private message';
const encoded_msg = steem.memo.encode(senderWif, receiverPubkey, msg);

const decoded_msg = steem.memo.decode(receiverWif, encoded_msg);

console.log(encoded_msg);
console.log(decoded_msg);
```

**Comment by oguzdelioglu** [comment]
> Hi, @oguzdelioglu
> Do you mean this?
> 
> ```
> const senderWif = '5JdeC9P7Pbd1uGdFVEsJ41EkEnADbbHGq6p1BwFxm6txNBsQnsw';
> const senderPubkey = 'STM8m5UgaFAAYQRuaNejYdS8FVLVp9Ss3K1qAVk5de6F8s3HnVbvA';
> const receiverWif = '5HzbTLPQM9qv5iBavcvTGNr9UrRbCWeNGdY1pEqKxTS567sh51F';
> const receiverPubkey = 'STM7oNQjZPQWkM4Qa3AZUP5WYRjkdYaGR1ciXepATvZ5xns2sPL5D';
> 
> const msg = '# this is a private message';
> const encoded_msg = steem.memo.encode(senderWif, receiverPubkey, msg);
> const decoded_msg = steem.memo.decode(receiverWif, encoded_msg);
> 
> console.log(encoded_msg);
> console.log(decoded_msg);
> ```

Yes.
I want to send it as a private message while transferring.I am using the message sending code below.

steem.broadcast.transfer(wifi,me,user,"0.001 STEEM",message

How can I include your code above in this code?

**Comment by oguzdelioglu** [comment]
steem.api.getAccounts([anamesi], function(err, accResult) {
const senderWif = wifi;
const receiverPubkey =  accResult[0].memo_key;
const msg = '# ' + wmesaji;
const encoded_msg = steem.memo.encode(senderWif, receiverPubkey, msg);
steem.broadcast.transfer(wifi,whalenamesi,anamesi,"0.001 STEEM",encoded_msg, function(err, result) {
              }
}

its worked.
