### ISSUE TITLE
Implement Plugin APIs

### ISSUE THREAD

**Issue by yamadapc** [steemit/steem-js#54]
- [ ] Implement `follow` plugin API https://github.com/steemit/steem/blob/01027e087b01a131c1ca75e29551377f14475065/libraries/plugins/follow/include/steemit/follow/follow_api.hpp
  * `get_follow_count` etc
- Review other unimplemented plugins

**Comment by sneak** [comment]
Following and tags are going to be moved out of steemd soon in favor of a separate process (to be open sourced in the next few days).  I would avoid implementing these functions yet.

**Comment by adcpm** [comment]
These methods been already implemented. Closing this ticket.
