### ISSUE TITLE
firefox date deserialization problem

### ISSUE THREAD

**Issue by dacom-dark-sun** [steemit/steem-js#56]
With Chrome all works fine, but in Firefox i have error when i broadcast a comment:
 
Error: 3030000 tx_missing_posting_auth: missing required posting authority
Missing Posting Authority sci
{"id":"sci","posting":{"weight_threshold":1,"account_auths":[["streemian",1]],"key_auths":[["STM8MfcHZyYioPBsmoYp8AZf4mbwZdsarunFRvuWUySqb3nwPeRwb",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM82cz4GKWWiEoikHfehMJ9PapecmoUsf4bE7NDoZD47PTBqSTK4",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM67rQk47AyFkSzw61CMdpKJEtFwwJr3QyFUpt9Wb54J9LDEyeea",1]]}}
    th_a  transaction.cpp:129 verify_authority

{"ops":[["comment",{"parent_author":"","parent_permlink":"test","author":"sci","permlink":"test-article-number-y","title":"test article (number y)","body":"tsst","json_metadata":"{\"tags\":[\"test\",\"news\",\"technologies\"],\"model\":\"news\",\"app\":\"mapala\",\"}"}]],"sigs":["STM7pQESd1aqnYbf9DFmZFScNpSudZn4PzCYgJ3udYos239913WYT"]}
    th_a  transaction.cpp:172 verify_authority

And key is always different. I had a same trouble with GolosJs, while im not install correct Chain-Id. Firstly, i think this is my local problem, but with SteemJs and transaction to Steem network - i have same answer in FireFox.. 

I use it PHP Yii2 application, just include steem.min.js and command: 

                steem.broadcast.comment(wif.plaintext, 
                trx['parentAuthor'], 
                trx['parentPermlink'], 
                trx['author'], 
                trx['permlink'], 
                trx['title'], 
                trx['body'], 
                trx['metadata'], 
                function(err, result) {
                    console.log(err, result);
     
                    if (err == null){
                        setTimeout(redirect, 6000);
                    } else alert(err);
            });

Simple, and work with Chrome.. But why firefox does not work?

**Comment by MrXtar** [comment]
+1 FireFox issue with escrow_transfer transaction.

**Comment by ruslansalikhov** [comment]
@adcpm  Hello. I see that issue in parsing date from string. Firefox think that date was passed on local time. And I see that you had commented fix for that issue (I don't know why you comment it?)

src/auth/serializer/src/types.js:408
        if(typeof object === "string" && !/Z$/.test(object))
            object = object + "Z"

Could you please tell why did you (or somebody other) do this? Thanks.

@MrXtar @dacom-dark-sun if you want use current version - Just add 'Z' symbol to you time strings (I mean - ratificationDeadline, escrowExpiration).

**Comment by jcalfee** [comment]
Chrome assumes a date string is a Zulu date with or without the Z but FF requires the Z.

I don't know why that is commenting out, I'm trying to trace it back into the Bitshares repository where we may have a commit message.

It is likely that we could enable it since this kind of issue would cause the date to serialize incorrectly in FF ever time.  In other words, I think you are the first to depend on this so it should be safe to enable it.  Lets see what we can learn from this commit history first though.

**Comment by ruslansalikhov** [comment]
BTW.. If anybody wants to use current version - just pass Date objects to steem-js functions, not strings.
