### ISSUE TITLE
Post views missing from post information

### ISSUE THREAD

**Issue by thrize** [steemit/steem-js#69]
_Nice template, great idea, I might use it ;)_

#### Expected behavior

Post data should contain a field with the number of views a post has had. This information should be available as it is presented on Steemit.com beside an eye symbol.

#### Actual behavior

No view field is available (or it is hidden / obfuscated as or within another field).

#### How to reproduce

Read any posts any way, e.g. ```steem.api.getDiscussionsByCreated( ... )```

Thanks guys :D

**Comment by roadscape** [comment]
Views are recorded off-chain on each frontend; thus, it is not the sort of data steem-js can access.

**Comment by thrize** [comment]
Hi @roadscape thanks for that, I wasn't aware at the time this was the case.
