### ISSUE TITLE
Add http support (non-websocket alternative) for read API calls

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem-js#72]
branch: [72-http-socket-support](https://github.com/steemit/steem-js/commits/72-http-socket-support)

**Comment by jcalfee** [comment]
- [ ] remove RPC login call

**Comment by jcalfee** [comment]
I was able to broadcast a vote via HTTP from `condenser/1119-websocket-to-http` using this branch `steem-js/72-http-socket-support`:

![image](https://cloud.githubusercontent.com/assets/204121/23864986/2da8a7aa-07e2-11e7-8f91-bbe82c4d778e.png)

**Comment by adcpm** [comment]
Great! do you feel broadcast is slow compare to websocket?

**Comment by jcalfee** [comment]
I don't know.. It all happened so fast. Lol .. It is not really about the speed of one call as it is about being able to assign requests to available instances.  Also, remember steemd still needs an upgrade and really needs to have a proper http server to allow for http optimizations.

If you really want to speed things up, you should program the UI to respond to the first event (transaction broadcast) then let the user move on before the second event comes in (trx accepted in a block).

**Comment by bonustrack** [comment]
Closing this issue as http support branch #209 has been merged on master
