### ISSUE TITLE
SteemJS streamOperations is returning a error code 301 for the ws connection.

### ISSUE THREAD

**Issue by unipsycho** [steemit/steem-js#82]
#### Expected behavior
steem.api.streamOperations(function (err, operations) { ...}
normally returns all streaming operations. 

#### Actual behavior
It is currently returning the following error:
**WebSocket connection to 'wss://steemit.com/wspa' failed: Error during WebSocket handshake: Unexpected response code: 301**

#### How to reproduce
run the example Stream.html from the release, or any product using the same stream.api like (https://autosteem.learnthis.ca)

The error code occurs immediately.  I've tried with the latest 0.4.7 in releases as well.

**Comment by adcpm** [comment]
It seem that the websocket on Steemit just moved. Please try using this ond instead: wss://steemd.steemit.com

**Comment by andrienpecson** [comment]
I'm currently experiencing this issue
