### ISSUE TITLE
Set chain properties

### ISSUE THREAD

**Issue by esteem8** [steemit/steem-js#92]
Providing an api function to set the "chain_id".

#### Expected behavior

Using the chain ID or chain name.

#### Actual behavior

Using a hack.

**Comment by adcpm** [comment]
Please try with version 0.4.10 https://github.com/steemit/steem-js/releases/tag/v0.4.10. There is a new method **steem.config.set**. You can use it like this: 
```
steem.config.set('chain_id','782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de12'); // Golos chain id
```
