### ISSUE TITLE
Return server's response after a transaction is broadcasted

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem-js#98]
The server returns some information about the transaction including a block number.  It is probably a good idea to include the server's response here too in the returned value:

https://github.com/steemit/steem-js/blob/8297117cc4712c5fa63f75dcf8431f4978950a8f/src/broadcast/index.js#L41

I just tested broadcastTransactionSynchronousAsync and got the following reply.  I expect to see the same reply format in the non-synchronous broadcast that is used in [master].

![image](https://cloud.githubusercontent.com/assets/204121/23864986/2da8a7aa-07e2-11e7-8f91-bbe82c4d778e.png)

I'm not sure who this might affect so I'm not going to make the change without feedback.

**Comment by adcpm** [comment]
Now we are using this response on Busy. Do you want that Steem.js answer with server response? The server will always respond with "null" on confirmation right?
